# Generated by Django 3.2.11 on 2022-02-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_booking',
        ),
        migrations.DeleteModel(
            name='PickTime',
        ),
    ]
