# Generated by Django 3.2.11 on 2022-02-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0002_auto_20220209_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nails.pickdate', unique=True),
        ),
    ]
