# Generated by Django 3.2.11 on 2022-02-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0003_alter_booking_date_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nails.pickdate'),
        ),
    ]
