# Generated by Django 3.2.11 on 2022-02-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0004_alter_booking_date_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nails.pickdate', verbose_name='Выберите дату посещения:'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ваше имя:'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Ваш номер сотового телефона:'),
        ),
    ]
