# Generated by Django 3.2.11 on 2022-02-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0005_auto_20220211_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='pickdate',
            options={'verbose_name': 'Доступные даты'},
        ),
    ]
