# Generated by Django 3.2.11 on 2022-02-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nails', '0007_auto_20220211_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nails.pickdate', verbose_name='Дата посещения:'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер сотового телефона:'),
        ),
        migrations.AlterField(
            model_name='pickdate',
            name='date_booking',
            field=models.CharField(blank=True, max_length=30, verbose_name='Доступная дата посещения'),
        ),
    ]
